### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by edgedalmacio** [socketry/multipart-post#1]
Hi, I'm new to ruby and I'm trying to use your gem to upload an image to ImageShack. I'm getting this error when I run the code below:

Execution:
MultipartPostTest.new

Source:
require 'rubygems'
require 'net/http/post/multipart'

class MultipartPostTest
  def initialize
    url = URI.parse('http://www.imageshack.us/upload_api.php')
    File.open('c:/x.jpg') do |jpg|
      req = Net::HTTP::Post::Multipart.new url.path,
        "fileupload" => UploadIO.new(jpg, "image/jpeg", 'c:/x.jpg')
      res = Net::HTTP.start(url.host, url.port) do |http|
        http.request(req)
      end
    end
  end
end

Trace:
EOFError: end of file reached
    from ruby/lib/ruby/1.8/net/protocol.rb:133:in `sysread'
    from ruby/lib/ruby/1.8/net/protocol.rb:133:in`rbuf_fill'
    from ruby/lib/ruby/1.8/timeout.rb:56:in `timeout'
    from ruby/lib/ruby/1.8/timeout.rb:76:in`timeout'
    from ruby/lib/ruby/1.8/net/protocol.rb:132:in `rbuf_fill'
    from ruby/lib/ruby/1.8/net/protocol.rb:116:in`readuntil'
    from ruby/lib/ruby/1.8/net/protocol.rb:126:in `readline'
    from ruby/lib/ruby/1.8/net/http.rb:2029:in`read_status_line'
    from ruby/lib/ruby/1.8/net/http.rb:2018:in `read_new'
    from ruby/lib/ruby/1.8/net/http.rb:1059:in`request'
    from test_project/lib/multipart_post_test.rb:11:in `initialize'
    from ruby/lib/ruby/1.8/net/http.rb:547:in`start'
    from ruby/lib/ruby/1.8/net/http.rb:440:in `start'
    from test_project/lib/multipart_post_test.rb:10:in`initialize'
    from test_project/lib/multipart_post_test.rb:7:in `open'
    from test_project/lib/multipart_post_test.rb:7:in`initialize'
    from (irb):1:in `new'
    from (irb):1>>

**Comment by ioquatix** [comment]
Can you please confirm if this is still an issue?

**Comment by sanjusoftware** [comment]
I tried all the above methods to no avail ... does anyone know what the real problem is ... looks like in this context does not have anything to do with net/http(s) because I see this error on following line:

```ruby
file = 'iron_man.jpg'
io = UploadIO.new(file, 'image/jpeg')
```
do we know why is that happening?

**Comment by ioquatix** [comment]
What error are you seeing?
