### ISSUE TITLE
Force warning

### ISSUE THREAD

**Issue by DariuszMusielak** [socketry/multipart-post#105]
Hello, 
I notice that in my project when I use Faraday 0.17.4 which depends on this gem I get warning:

> "Top level ::MultipartPost is deprecated, require 'multipart/post' and use `Multipart::Post` instead!"

I checked the code and see that [here](https://github.com/socketry/multipart-post/blob/main/lib/multipart_post.rb#L7) does a force `warn` no matter what. Why is it done in that way?

**Comment by nroose** [comment]
Also, seems like the standard for deprecation warnings is to have the message start with DEPRECATION_WARNING. I use this in filters to track and manage deprecations. Please change to use this standard.

**Comment by nroose** [comment]
And many deprecation warnings include the calling line number and that is very convenient!

**Comment by ioquatix** [comment]
Feel free to submit a PR if you can think of a way to improve it.

**Comment by ioquatix** [comment]
BTW, this issue was fixed in Faraday: https://github.com/lostisland/faraday/commits/0.1x

I'm going to close, this, but if you want to add more information to the warnings, please feel free to open a PR.
