### ISSUE TITLE
The Content-Length does not byte-size, in Ruby 1.9.2-p290.

### ISSUE THREAD

**Issue by koshigoe** [socketry/multipart-post#13]
- Ruby 1.9.2-p290
- Request body include Japanese characters (UTF-8)

String#length returns charactor length. Not byte-size.
String#bytesize returns length of string in bytes.

**Comment by ioquatix** [comment]
I believe this is fixed, but there might be other issues since the code is pretty old. We should definitely be using `bytesize` everywhere now. If you have time, a check and PR would be awesome.
