### ISSUE TITLE
Allow UploadIO to accept additional MIME headers as options

### ISSUE THREAD

**Issue by dmolesUC** [socketry/multipart-post#45]
The `UploadIO` initializer accepts a list of options and uses them to construct MIME headers, but it only pulls out headers it knows about. It would be nice to be able to include arbitrary headers.

For an example use case, see the `Packaging` and `Content-MD5` headers in the [SWORD 2.0](http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#protocoloperations_addingcontent_multipart) spec, e.g.

```
Content-Type: application/zip
Content-Disposition: attachment; name=payload; filename=[filename]
Packaging: http://purl.org/net/sword/package/SimpleZip
Content-MD5: [md5-digest]
MIME-Version: 1.0

...binary package data...
```

**Comment by ioquatix** [comment]
I think this is a good idea.

**Comment by ioquatix** [comment]
Are we good to close this issue?

**Comment by dmolesUC** [comment]
@ioquatix Yep, thanks! (Sorry, should have thought to do it after the PR was merged.)

**Comment by ioquatix** [comment]
Thanks!
