### ISSUE TITLE
3.0 release changes

### ISSUE THREAD

**Issue by ioquatix** [socketry/multipart-post#48]
I'm trying to figure out who is depending on `multipart-post` so we can get everyone on board for a 3.0 release

https://github.com/lostisland/faraday/issues/689

**Comment by patrickdavey** [comment]
I just came to open an issue about the use of the top level modules in here (specifically `Part` and `Parts`, which conflicts with a project I'm working on). You've already raised the point [here](https://github.com/lostisland/faraday/issues/689#issue-225856162).

As it has been more than 2 years I'm guessing you've decided not to release 3.0, at least in the short term? Anyway, just wanted to 👍 the idea of namespacing the code.

👋 by the way ! hadn't realised you were maintaining the gem :)

**Comment by ioquatix** [comment]
We should fix it. It’s a huge mess. Want to have a go at submitting a PR?

**Comment by patrickdavey** [comment]
Yip, with hacktoberfest coming up I'll definitely give it a go. :)

If you're happy, I'll start small and just do a series of incremental refactorings. Do you want me to do PRs into `master` or do you want to make a `3.0` branch (or similar)? 

I'll just plan to make the module system more sane and out of the top level. Basically scratch my own itch ;)

**Comment by ioquatix** [comment]
That all sounds good make small incremental changes then I can give you incremental feedback ;)

**Comment by ioquatix** [comment]
I will give you commit access don’t bother with a fork, let’s work on feature branches and we can merge into master

**Comment by patrickdavey** [comment]
I've just split the `parts` out into its own namespace. Tests are running green (though I haven't tested how good the coverage is). Anyway, if you have time and want to comment on whether this is the approach you'd take -> https://github.com/socketry/multipart-post/compare/master...refactor_parts_into_mutlipart_post_namespace

Very happy to be guided by you on how you want to go about this process, do you want me to just open a PR once I'm happy with a chunk of work (like this refactoring of `Parts`?). 

To be very cheeky, I might wait until Oct 1st to open any PR ;) . Thanks very much for the opportunity to work on this with you!

**Comment by ioquatix** [comment]
@patrickdavey your work here is merged into master, and I think we can prepare a 3.0 release pretty soon.
