### ISSUE TITLE
Changes in v2.1.0

### ISSUE THREAD

**Issue by Domon** [socketry/multipart-post#60]
Hi, 👋 

`v2.1.0` is not listed in [History.txt](https://github.com/socketry/multipart-post/blob/063de4b2cfd95bc12c4a300506674fb9d35600f8/History.txt).

Is there any change that a user should know?

Thanks.

**Comment by ioquatix** [comment]
https://github.com/socketry/multipart-post/compare/v2.0.0...master

The use of a static boundary was a security issue, so it was fixed. That was the main change. Almost everything else was just general maintenance to keep the lights on.

Do you want to submit a PR to update the `History.txt`?

**Comment by ioquatix** [comment]
I have removed `History.txt` as it is out of date (last updated 2013).
