### ISSUE TITLE
Does multipart-post follow Semantic versioning?

### ISSUE THREAD

**Issue by jspanjers** [socketry/multipart-post#63]
For gems depending on multipart-post that want to add a pessimistic version constraint (e.g.  '~> 2.2'), it is useful to know if multipart-post follows the semantic versioning scheme.

I tend to believe it is, but I cannot find it in the README.

**Comment by ioquatix** [comment]
Yes

**Comment by ioquatix** [comment]
Feel free to submit a PR to the readme
