### ISSUE TITLE
Can you push a new version to RubyGems? 🙏🏻 

### ISSUE THREAD

**Issue by timrogers** [socketry/multipart-post#81]
Would there be any chance of releasing a new version of this package to RubyGems?

There've been a bunch of exciting changes - for example https://github.com/socketry/multipart-post/pull/70 - but they're only accessible by installing from GitHub rather than using a versioned, released package.

**Comment by timrogers** [comment]
Thank you in advance 🙇🏻

**Comment by olleolleolle** [comment]
The work to create a usable release is listed in https://github.com/socketry/multipart-post/issues/82

**Comment by ioquatix** [comment]
https://github.com/socketry/multipart-post/releases/tag/v2.2.0
