### ISSUE TITLE
Release a 2.2.0

### ISSUE THREAD

**Issue by olleolleolle** [socketry/multipart-post#82]
- [x] CHANGELOG items from https://github.com/socketry/multipart-post/compare/v2.1.1...master - if you see something that's a feature, or notable, make a comment here, so we can source a CHANGELOG section for this version.
- [x] bump minor (there are tiny features)
- [x] release the gem

**Comment by ioquatix** [comment]
https://github.com/socketry/multipart-post/releases/tag/v2.2.0
