### ISSUE TITLE
Specify correct Ruby version required in 2.2.0

### ISSUE THREAD

**Issue by tnir** [socketry/multipart-post#92]
In [v2.2.0](https://github.com/socketry/multipart-post/releases/tag/v2.2.0) ([RubyGems.org v2.2.0](https://rubygems.org/gems/multipart-post/versions/2.2.0)), dropped Ruby 2.2 support due to #91.

Specify the version in the gemspec. @ioquatix thoughts?

- ruby/ruby@83cd51e3fe6e1e2be1375602274caa6ae0ac2a86

```
From 83cd51e3fe6e1e2be1375602274caa6ae0ac2a86 Mon Sep 17 00:00:00 2001
From: nobu <nobu@b2dd03c8-39d4-4d8f-98ff-823fe69b080e>
Date: Thu, 30 Jul 2015 04:20:00 +0000
Subject: [PATCH] variable.c: Module#deprecate_constant

* variable.c (rb_const_get_0): warn deprecated constant reference.
* variable.c (rb_mod_deprecate_constant): mark constants to be
  warned as deprecated.  [Feature #11398]

git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@51444 b2dd03c8-39d4-4d8f-98ff-823fe69b080e
```

**Comment by tnir** [comment]
#75 dropped Ruby 2.0.x, 2.1.x, 2.2.x, 2.3.x, 2.4.x and 2.5.x from testing.

**Comment by tnir** [comment]
@ioquatix Thank you for triaging #93 quickly. Are you doing `gem yank multipart-post -v 2.2.0` after the release of 2.2.1 with #93?

**Comment by ioquatix** [comment]
Is it safe to yank a release that people have in their lock files already?

**Comment by tnir** [comment]
I think it is safe when you yank 2.2.0 after you release 2.2.1. You can wait for 1 month as grace period after 2.2.1 is published.

**Comment by deivid-rodriguez** [comment]
I wouldn't recommend yanking because I don't think the benefits (some Ruby 2.2 users being able to skip a bad upgrade) outweigh the drawbacks (some modern Ruby users happily using 2.2.0 suddenly getting errors).

**Comment by ioquatix** [comment]
I am happy to release a new version with this version guard.
