### ISSUE TITLE
Please inlcude README / LICENSE file into the package.

### ISSUE THREAD

**Issue by voxik** [socketry/multipart-post#97]
Trying to update multipart-post package for Fedora, I have noticed there is not license file included [[1]]. Could you please consider to including one? I think that inclusion of the README would be nice at minimum.

[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by ioquatix** [comment]
Sure, I'll update it.

**Comment by ioquatix** [comment]
There is now a `license.md` which lists all authors.
